kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  name: sample
  namespace: test
  labels:
    build: sample_2
spec:
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: sample:latest	
  output:
    to:
      kind: DockerImage
      name: quay.io/at83104/sample
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'sample:latest'
