kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"demo:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"demo\")].image"}]
  name: demo
  namespace: security-test
  labels:
    app: demo
    app.kubernetes.io/component: demo
    app.kubernetes.io/instance: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: demo
  template:
    metadata:
      labels:
        deployment: demo
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      serviceAccountName: spo-deploy-sa
      securityContext:
        seLinuxOptions:
          type: allow_security-test.process      
      containers:
        - name: demo
          image: >-
            image-registry.openshift-image-registry.svc:5000/test/demo@sha256:40235a653660b4f776776dd44c72674b18e8287ae8244ca2a41664fd7b0882f6
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
