apiVersion: v1
kind: ServiceAccount
metadata:
  name: spo-deploy-test
  namespace: security-test
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spo-test
  namespace: security-test
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spo-test
  namespace: security-test
subjects:
- kind: ServiceAccount
  name: spo-deploy-test
roleRef:
  kind: Role
  name: spo-test
  apiGroup: rbac.authorization.k8s.io  